name = "Sensemakr"
uuid = "b1eed063-bea0-4e2a-bcc5-a02b2b0a7b77"
authors = ["Rodrigo Grijalba", "Alexander Quispe"]
version = "0.1.0"

[compat]
julia = "1.8.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
